### ISSUE TITLE
Locale failed

### ISSUE THREAD

**Issue by tomerf-sndbox** [ibmresilient/resilient-community-apps#38]
I'm trying to install fn_vmray_analyzer.

Getting error after running customization command regarding locale:

`-bash-4.2$ resilient-circuits customize
Unverified HTTPS requests (cafile=false).
Package 'fn-vmray-analyzer 1.0.0':
    OK to import customizations from 'fn-vmray-analyzer 1.0.0'? (y/n):y
Failed, importing customizations from 'fn-vmray-analyzer 1.0.0'
Traceback (most recent call last):
  File "/usr/local/bin/resilient-circuits", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/resilient_circuits/bin/resilient_circuits_cmd.py", line 638, in main
    customize_resilient(args)
  File "/usr/local/lib/python2.7/site-packages/resilient_circuits/util/resilient_customize.py", line 119, in customize_resilient
    do_customize_resilient(client, entry_points, args.yflag, args.install_list)
  File "/usr/local/lib/python2.7/site-packages/resilient_circuits/util/resilient_customize.py", line 156, in do_customize_resilient
    customizations.load_import(definition, dist)
  File "/usr/local/lib/python2.7/site-packages/resilient_circuits/util/resilient_customize.py", line 211, in load_import
    result = self.client.post(uri, import_data)
  File "/usr/local/lib/python2.7/site-packages/resilient/co3.py", line 300, in post
    _raise_if_error(ex.get_response())
  File "/usr/local/lib/python2.7/site-packages/resilient/co3.py", line 163, in _raise_if_error
    raise SimpleHTTPException(response)
resilient.co3.SimpleHTTPException: Bad Request:  {"success":false,"title":null,"message":"Unable to process the supplied JSON.  The field 'locale' is not recognized.  The error occurred at line #1 and column #16.","hints":[],"error_code":"generic"}`

**Comment by MarkScherfling** [comment]
Hi Tomer,

This is related to the version of resilient and an incompatibility with this integration. But it should be fixable with a small update. What version of resilient are you running?

Mark

**Comment by tomerf-sndbox** [comment]
Hi Mark,

The installed version is (latest?): 30.0.3476

Tomer.

**Comment by MarkScherfling** [comment]
Hi Tomer,
 
Thanks. This integration works with Resilient v31 or greater. I'm surprised you didn't get a different message indicating the version mismatch.
 
Sorry for not being able to help further.
                                                                        Mark Scherfling                        Engineering Manager                                                                        
                                                                                                                                m: +1 978-835-4530                        e: mark.scherfling@ibm.com                                                 
 
 
 
----- Original message -----From: Tomer Frid <notifications@github.com>To: ibmresilient/resilient-community-apps <resilient-community-apps@noreply.github.com>Cc: MarkScherfling <mark.scherfling@ibm.com>, Comment <comment@noreply.github.com>Subject: Re: [ibmresilient/resilient-community-apps] Locale failed (#38)Date: Mon, Apr 22, 2019 12:00 PM 
Hi Mark,
The installed version is (latest?): 30.0.3476
Tomer.
—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tomerf-sndbox** [comment]
Hi Mark,

How it possible to upgrade the resilient platform?
