### ISSUE TITLE
Hello, I have created an application and i need to push it here , Anyone could help?

### ISSUE THREAD

**Issue by osama6162** [ibmresilient/resilient-community-apps#46]

**Comment by breid1313** [comment]
Hi @osama6162 ! We welcome community submissions. The best route is to go through the submission portal on the X-Force App Exchange. Try this link: https://exchange.xforce.ibmcloud.com/hub/dashboard

Let me know if you need anything!

**Comment by osama6162** [comment]
@breid1313 
Thank you so much!
I have submitted my SMG App 
I have a question, Do you know when will it be uploaded to Community apps or do you know how long does the process take by ibm reviewing my app to be uploaded?

Thanks

**Comment by breid1313** [comment]
@osama6162 Awesome! No problem.

Regarding your question, do you mean the time to validate the App and get it on the App Exchange or the time to get the code into the resilient-community-apps repository. Not all App that get published on the App Exchange get added to this repo.

**Comment by breid1313** [comment]
As for getting it validated and up on AppX, but really depends on the App. Big factors are documentation, number of functions provided with the app, and the availability of a test environment if applicable.

**Comment by osama6162** [comment]
@breid1313  
Yes, am asking about the time to validate the App and get it on the App Exchange..
i have inserted all documentation so, am waiting.

**Comment by breid1313** [comment]
@osama6162 Awesome! Thank you for including docs.

I'm not one of the people that generally does validations, but I went ahead and took a quick look at the app anyways. Nothing looks out of place at first glance, which is great! I did notice that your `config.py` doesn't add any updates to my `app.config` when I run `resilient-circuits config -u` but that's going to be an easy fix.

I'm creating a ticket for this internally now so that it can get groomed and we'll get one of our validators to work with you on this. Thanks again for submitting!

**Comment by osama6162** [comment]
@breid1313 
Thanks for your valuable notice, i have resolved the issue of not updating app.config file, and now working fine..
i'll be waiting the validator contacting me to resend the fixed package again or advice with the process to resend the fixed package in order to be reviewed to be uploaded to App Exchange..

Thanks @breid1313

**Comment by breid1313** [comment]
@osama6162 Excellent! Thanks for reaching out and I'm excited that this was submitted for validation. I'm going to close the issue, since it was submitted and I created the ticket.

**Comment by osama6162** [comment]
Thanks @breid1313 :)

**Comment by osama6162** [comment]
Hello @breid1313 

Hope your having a good day.

Sorry if bothering you..
Actually, I have two questions regarding to "IBM APP Exchange - Resilient - Community Apps"

I have submitted Symantec Messaging Gateway "SMG"  at Jul 14, 2020
Symantec Messaging Gateway (SMG) Version 1.0.0
Symantec Messaging Gateway - SMG Version 1.0.1 "with bug fix of not updating app.config file"

to be reviewed with all documentation and followed all steps..

My 1st question is:

Why have got my Version 1.0.0 app (rejected) with no justification or mail with clarification?

My 2nd question is:

When will i receive respond to my Version 1.0.1 app as it still with (submitted) status although, i have uploaded both version on same date ?

BR,

**Comment by MarkScherfling** [comment]
Greetings,
 
I can answer the question why the 1.0.0 submission was rejected. If you go into to submission rejection, a note was added to indicate that this looked like an overlapping submission as you had also submitted a 1.0.1 version. If this is in error and you are intending to have both published, you can resubmit for validation.
 
Regards,
                                                                        Mark Scherfling                        Engineering Manager                                                                        
                                                                                                                                m: +1 978-835-4530                        e: mark.scherfling@ibm.com                                                 
 
 
 
----- Original message -----From: osama6162 <notifications@github.com>To: ibmresilient/resilient-community-apps <resilient-community-apps@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] Re: [ibmresilient/resilient-community-apps] Hello, I have created an application and i need to push it here , Anyone could help? (#46)Date: Sun, Jul 19, 2020 10:34 AM 
 
Hello @breid1313
Hope your having a good day.
Sorry if bothering you..Actually, I have two questions regarding to "IBM APP Exchange - Resilient - Community Apps"
I have submitted Symantec Messaging Gateway "SMG" at Jul 14, 2020Symantec Messaging Gateway (SMG) Version 1.0.0Symantec Messaging Gateway - SMG Version 1.0.1 "with bug fix of not updating app.config file"
to be reviewed with all documentation and followed all steps..
My 1st question is:
Why have got my Version 1.0.0 app (rejected) with no justification or mail with clarification?
My 2nd question is:
When will i receive respond to my Version 1.0.1 app as it still with (submitted) status although, i have uploaded both version on same date ?
BR,
—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by osama6162** [comment]
@MarkScherfling 

Thanks for you reply..

Actually there is no note added but, anyway i understand now that the rejection for version 1.0.0 is due to duplication.
it will be so nice if u have answer to My 2nd question:
When will i receive respond to my Version 1.0.1 app as it still with (submitted) status although, i have uploaded both version on same date ?

BR,

**Comment by MarkScherfling** [comment]
The submission is in our queue. When a validator free's up, they will contact you regarding the solution. We have a checklist of items which we review and it there may be some back and forth discussion with the validator on our submission.  I would expect you should be hearing about the process within the week.
 
Regards,
                                                                        Mark Scherfling                        Engineering Manager                                                                        
                                                                                                                                m: +1 978-835-4530                        e: mark.scherfling@ibm.com                                                 
 
 
 
----- Original message -----From: osama6162 <notifications@github.com>To: ibmresilient/resilient-community-apps <resilient-community-apps@noreply.github.com>Cc: MarkScherfling <mark.scherfling@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [ibmresilient/resilient-community-apps] Hello, I have created an application and i need to push it here , Anyone could help? (#46)Date: Mon, Jul 20, 2020 10:30 AM 
 
@MarkScherfling
Thanks for you reply..
Actually there is no note added but, anyway i understand now that the rejection for version 1.0.0 is due to duplication.it will be so nice if u have answer to My 2nd question:When will i receive respond to my Version 1.0.1 app as it still with (submitted) status although, i have uploaded both version on same date ?
BR,
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by osama6162** [comment]
@MarkScherfling  

Thank u so much!

**Comment by osama6162** [comment]
@MarkScherfling  
hello i hope your having a good day
Actually i didn't hear anything from either none of validator's team or dev team.
advice plz
Many Thanks
