### ISSUE TITLE
How to authenticate in funtion Call REST API?

### ISSUE THREAD

**Issue by jdelcol** [ibmresilient/resilient-community-apps#6]
How to authenticate in funtion Call REST API?

**Comment by hpyle** [comment]
That will depend on the requirements of the service, since there are several different styles of authentication.  Do you have a specific service that you're asking about?

I'm going to close this issue here, since it's not a software problem report.  Please follow up with this (and other "how..." questions) on the [community forums](http://ibm.biz/resilientcommunity).
